### ISSUE TITLE
Missing type: object

### ISSUE THREAD

**Issue by ndreno** [outscale/osc-api#18]
Hi there,

Correct me if I'm wrong but I feel 'ReadKeypairsResponse' is the only one without an explicit object type declaration:
https://github.com/outscale/osc-api/blob/master/outscale.yaml#L7165

Is it possible to add it as our code gen tooling is raising that as error (depending on tooling, some are more sensitive than others...)

**Comment by GMercat** [comment]
Hi,

Thanks for your comment. It will be fix in the next update soon.

**Comment by outscale-gmt** [comment]
Fixed her : https://github.com/outscale/osc-api/commit/626fe33d398d3075f3241affc2e2ffd2d24ee639#diff-d61f0294fc98461c6ec43412ad5b5fab6988de0292c1db7fea1cfa27bcf0c06dR7175
